---

- name: "Test if UCP controller is up"
  uri:
    url: "https://{{ ucp_fqdn }}/_ping"
    validate_certs: no
  register: ucp_primary
  ignore_errors: yes

- name: "Add license file"
  copy:
    src: "docker_subscription.lic"
    dest: /tmp
  when: ucp_primary.status != 200

- name: "Install primary UCP controller"
  command: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/docker_subscription.lic:/docker_subscription.lic -e UCP_ADMIN_PASSWORD={{ ucp_admin_password }} --name ucp docker/ucp:1.1.1 install --host-address {{ ansible_default_ipv4['address'] }} --san {{ ansible_fqdn }} --san {{ ucp_fqdn }}
  when: ucp_primary.status != 200

