---

- name: "Test if UCP primary controller already exists"
  uri:
    url: "https://{{ ucp_fqdn }}/_ping"
    validate_certs: no
  register: ucp_primary
  ignore_errors: yes

- include: ucp-primary.yml
  when: status.stdout != "200"

