---

- name: "Test if UCP controller is up"
  uri:
    url: "https://{{ ucp_fqdn }}/_ping"
    validate_certs: no
  register: ucp_primary
  ignore_errors: yes

- include: ucp-primary.yml
  when: ucp_primary.status != 200

