---

- name: "Test if UCP primary controller already exists"
  shell: "curl --insecure --silent --output /dev/null --write-out '%{http_code}' https://{{ ucp_fqdn }}/_ping"
  register: status

- include: ucp-primary.yml
  when: status.stdout != "200"

