---

- name: "devicemapper: Install LVM2"
  become: yes
  yum:
    name: lvm2
    state: present

- name: "devicemapper: Create volume group"
  become: yes
  lvg:
    vg: docker
    pvs: "{{ dm_device }}"
    state: present

- name: "devicemapper: Create logical volume"
  become: yes
  lvol:
    lv: thinpool
    vg: docker
    size: 85%VG
    opts: "--thin"
    state: present
