---

- name: "devicemapper: Install LVM2"
  become: yes
  yum:
    name: lvm2
    state: present

- name: "devicemapper: Create volume group"
  become: yes
  lvg:
    vg: docker
    pvs: "{{ dm_device }}"
    state: present

- name: "devicemapper: Create logical volume"
  become: yes
  lvol:
    lv: thinpool
    vg: docker
    size: 95%VG
    opts: "--thin"
    state: present

- name: "devicemapper: Add LVM Profile"
  copy:
    src: "docker-thinpool.profile"
    dest: /etc/lvm/profile
    owner: root
    group: root

- name: "devicemapper: Apply LVM Profile"
  become: yes
  command: lvchange --metadataprofile docker-thinpool docker/thinpool

