---

- name: "devicemapper: Install LVM2"
  become: yes
  yum:
    name: lvm2
    state: present

- name: "devicemapper: Create volume group"
  become: yes
  lvg:
    vg: docker
    pvs: "{{ dm_device }}"
    state: present
