---

- include: ucp-iptables.yml

- name: "Copy images to host"
  copy:
    src: "{{ ddc_images }}"
    dest: /tmp
  when: ddc_images is defined

- name: "Load images in Docker engine"
  command: docker load -i /tmp/{{ ddc_images }}
  when: ddc_images is defined

- name: "Wait for UCP controller to come up"
  uri:
    url: "https://{{ hostvars[groups['ucp-primary'][0]]['ansible_eth0']['ipv4']['address'] }}/_ping"
    validate_certs: no
  register: ucp_primary
  until: ucp_primary.status == 200
  retries: 50
  delay: 2

- name: "Join replica to cluster"
  command: docker swarm join --token {{ hostvars[groups['ucp-primary'][0]]['master_token'].stdout }} {{ hostvars[groups['ucp-primary'][0]]['ansible_eth0']['ipv4']['address'] }}

